apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-k8s-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-k8s-reader
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: default