apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: spring-k8s-reader
rules:
  - apiGroups: [""]
    resources: ["pods","services","secrets","endpoints","configmaps"]
    verbs: ["get", "watch", "list","update"]
    
    