spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 129496
  redis:
    password: 129496
neiko:
  shiro:
    jwt:
      filter:
        jwt-url-list: 
          - /shiro/test

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
