neiko:
  redis:
    key-prefix: 'neiko-'
    null-value: 'N_V'
    delimiter: ':'
    thread-count: 10
    expire-time: 3600
  

server:
  port: 9090
  
# spring配置
spring:
  # redis
  redis:
    host: 120.25.221.239
    database: 0
    port: 6379
    password: Schilings11538...

# sa-token配置
sa-token:
  token-name: access_token
#  token-prefix: 'Bearer'
  auto-renew: false
  is-log: true
  is-concurrent: true
  timeout: 3600
  activity-timeout: 1800


    