spring:
  data:
    redis:
      host: 120.25.221.239
      database: 0
      port: 6379
      password: Schilings11538...
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nk_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WNs11538...
    