server:
  port: 8080
spring:
  redis:
    host: 120.25.221.239
    database: 0
    port: 6379
    password: Schilings11538...
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nk?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: WNs11538...

mybatis-plus:
  mapper-locations:
    - classpath*:/com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml #自动建表
    - classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# sa-token配置
sa-token:
  token-name: access-token
  auto-renew: true
  is-log: true
  is-concurrent: false

## 数据库表结构维护
actable: 
  table: 
    auto: none #update
  model: 
    pack: com.schilings.neiko.**.model.entity
  database: 
    type: mysql

## OPEN API接口文档
springdoc:
  swagger-ui:
    enabled: true
    urls: #由于 knife4j 对于规范支持的不全面，无法直接使用单文档源数据，所以必须进行分组或者 urls 的指定。
      - { name: 'sample', url: '/v3/api-docs' }