server:
  port: 9000

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO 
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.data.redis: TRACE

# 数据库表结构维护
#actable:
#  table:
#    auto: none #update
#  model:
#    pack: com.schilings.**.model.entity
#  database:
#    type: mysql

# 数据库版本控制维护
#spring:
#  flyway:
#    clean-disabled: true
#    baseline-on-migrate: true
#    placeholder-replacement: false # 取消占位符检测
  

# mybatis plus配置
mybatis-plus:
  mapper-locations:
    - classpath*:/com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml #自动建表
    - classpath*:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


## OPEN API接口文档
springdoc:
  swagger-ui:
    enabled: true
    urls: 
      - { name: 'sample', url: '/v3/api-docs' }
  
# spring配置
spring:
  profiles:
    active: 
      - neiko 
      - prod
  config:
    import: 
      - optional:file:E:\Code\neiko-all-version\1.0.0\neiko\database\oauth2\oauth2-client-registration.yml
  # JavaMailSender 邮件发送的配置
  mail:
    #以qq邮箱发送
    host: smtp.qq.com
    username: 1146830743@qq.com
    #QQ邮箱的授权码
    password: dsejzvaoazwnhjbb
    properties:
      from: 1146830743@qq.com
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  
  
  
  
