server:
  port: 9000
logging:
  level:
    root: INFO
    org.springframework.web: INFO #filter
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

spring:
  profiles:
    active: client,resourceserver

