server:
  port: 8000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: ERROR
    

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          introspection-uri: http://localhost:9000/oauth2/introspect
#          # 远程令牌自省 客户端验证开启Basic验证
#          client-id: messaging-client
#          client-secret: secret
#        jwt:
#          issuer-uri: http://localhost:9000


neiko:
  security:
    oauth2:
      resourceserver:
        opaquetoken: # 远程令牌自省 客户端验证开启Basic验证
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: messaging-client
          client-secret: secret
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
          jws-algorithms: 
            - RS256
          public-key-location: 'C://1.txt'
          #audiences: 
          #  - 1
          #  - 2
        
        ignore-urls:
          - /error/**
          - /public/**
          - /ws/**
          - /actuator/**
          - /doc.html
          - /v2/api-docs/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
          - /swagger-ui.html
          - /webjars/**
          - /bycdao-ui/**
          - /favicon.ico
          - /captcha/**
          - /h2-console/**
